import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Poppins } from 'next/font/google';
import './globals.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCircleXmark } from '@fortawesome/free-solid-svg-icons';
import React from 'react';
import Header from './Header';
import Footer from './Footer';
// import { Provider } from 'react-redux';
import { Providers } from './GlobalRedux/provider';

const inter = Inter({ subsets: ['latin'] });
const poppins = Poppins({ weight: '500', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

// interface LogInDialogProps {
//   isVisible?: boolean;
// }

// const LogInDialog: React.FC<LogInDialogProps> = ({ isVisible }) => {
//   if (!isVisible) {
//     return null;
//   }
//   return (
//     <div className=" fixed inset-0 bg-black bg-opacity-25 backdrop-blur-sm flex justify-center items-center">
//       <div className=" w-[600px] flex flex-col relative">
//         <button type="button" className=" place-self-end relative top-5 left-5">
//           <FontAwesomeIcon
//             icon={faCircleXmark}
//             width={50}
//             className="text-gray-50"
//           />
//         </button>
//         <div className="bg-white p-2 rounded">log in modal</div>
//       </div>
//     </div>
//   );
// };
